//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lis_Lib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audiobook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Audiobook()
        {
            this.Carts = new HashSet<Cart>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public decimal Cost { get; set; }
        public System.TimeSpan Running_time { get; set; }
        public Nullable<byte> Abridged { get; set; }
        public string Language { get; set; }
        public Nullable<System.DateTime> Release_date { get; set; }
        public string Image { get; set; }
        public Nullable<int> Author_Id { get; set; }
        public Nullable<int> Genre_Id { get; set; }
        public Nullable<int> Narrator_Id { get; set; }
        public Nullable<int> Publisher_Id { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Narrator Narrator { get; set; }
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
    }
}
