//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lis_Lib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Order
    {
        public int Id { get; set; }
        public string User_Id { get; set; }
        public System.DateTime Order_date { get; set; }
        public string Cart_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Cart Cart { get; set; }
    }
}
