//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lis_Lib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public string Id { get; set; }
        public Nullable<int> Item_Id { get; set; }
        public byte[] Date { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
